// 使用隔离 DOM 验证活动路由，不连接用户桌面。
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('../windows/node_modules/jsdom');
const source = fs.readFileSync('codexBar/Resources/desktop-thread-route.js', 'utf8');
const dom = new JSDOM('<body><section id="old"><div contenteditable="true"></div></section><section id="new"><div contenteditable="true"></div></section></body>', {runScripts:'outside-only'});
const w = dom.window;
const editors = [...w.document.querySelectorAll('[contenteditable]')];
const route = id => ({routeKind:'local-thread',conversationId:id,pathname:'/thread/'+id,hostId:'local'});
const fiber = value => ({memoizedProps:{value},return:null});
editors.forEach((el,i) => { el.getClientRects = () => [{}]; el.__reactFiber$test = fiber(route(i ? 'new' : 'old')); });
const read = () => JSON.parse(w.eval(source));
w.document.getElementById('old').hidden = true;
assert.equal(read().conversationID,'new');
w.document.getElementById('old').hidden = false;
w.document.getElementById('new').style.display = 'none';
assert.equal(read().conversationID,'old');
w.document.getElementById('new').style.display = '';
assert.equal(read().routeKind,'unavailable', '多个可见对话不猜测目标');
w.document.getElementById('old').setAttribute('inert','');
assert.equal(read().conversationID,'new');
const committed = fiber(route('committed'));
const root = {stateNode:{current:null}}; const oldRoot = {stateNode:root.stateNode}; root.stateNode.current = root;
committed.return = root;
editors[1].__reactFiber$test = {...fiber(route('stale')),return:oldRoot,alternate:committed};
assert.equal(read().conversationID,'committed','DOM 旧 fiber 应读取已提交 alternate');
committed.memoizedProps.value = {routeKind:'home',pathname:'/'};
assert.equal(read().routeKind,'home');
committed.pendingProps = {value:route('pending')};
assert.equal(read().routeKind,'home','不能读取未提交属性');
committed.memoizedProps.value = {...route('remote'),hostId:'ssh-host'};
assert.equal(read().routeKind,'unavailable');
committed.memoizedProps = {value:{routeKind:'settings',pathname:'/settings'}};
assert.equal(read().routeKind,'settings','设置页不能误当首页');
committed.memoizedProps = {value:route('committed')};
const settings = {availableOptions:[],isLoading:false,selectedServiceTier:'priority',serviceTierForRequest:'priority'};
committed.updateQueue = {memoCache:{data:[[settings]]}};
assert.equal(read().serviceTier,'priority','读取官方编译器保存的速度设置');
settings.selectedServiceTier = null; settings.serviceTierForRequest = null;
assert.equal(read().serviceTier,'default','明确的 null 表示标准速度');
settings.isLoading = true;
assert.equal(read().serviceTierKnown,false,'加载中不能误认为标准模式');
settings.isLoading = false; settings.serviceTierForRequest = 'fast';
const toolbar = w.document.createElement('button');
w.document.getElementById('new').className = '_ComposerLayoutRoot_test';
w.document.getElementById('new').append(toolbar);
toolbar.getClientRects = () => [{}];
toolbar.__reactFiber$test = {memoizedProps:{settings},return:committed};
delete committed.updateQueue;
assert.equal(read().serviceTier,'fast','从同一编辑器的工具栏兄弟组件读取速度');
toolbar.hidden = true;
// 真实编译器缓存存在长行，速度对象可能位于第 100 个槽之后。
const longRow = Array(180).fill(null); longRow[160] = settings;
committed.updateQueue = {memoCache:{data:[longRow]}};
assert.equal(read().serviceTier, 'fast', '长缓存行中的速度设置不能截断');
const longCache = Array.from({length:140}, () => []); longCache[130] = [settings];
committed.updateQueue = {memoCache:{data:longCache}};
assert.equal(read().serviceTier, 'fast', '后部自定义 hook 缓存必须可读取');
delete committed.updateQueue;
const hookTail = {memoizedState:settings};
let hookHead = hookTail;
for (let i=0;i<12;i++) hookHead = {memoizedState:null,next:hookHead};
committed.memoizedState = hookHead;
assert.equal(read().serviceTier, 'fast', 'hook 链表不受普通对象深度限制');
delete committed.memoizedState;
toolbar.hidden = false;
// 实际富文本 DOM 无 fiber，最近宿主到根有 201 层。
const attached = editors[1].__reactFiber$test;
delete editors[1].__reactFiber$test;
const parent = w.document.getElementById('new');
let deep = {memoizedProps:{value:route('committed'),settings},return:null};
for(let i=0;i<201;i++) deep = {memoizedProps:{},return:deep};
parent.__reactFiber$test = deep;
toolbar.hidden = true;
assert.equal(read().conversationID, 'committed', '从编辑器父级宿主恢复真实路由');
assert.equal(read().serviceTier, 'fast', '201 层祖先链仍可识别 Fast');
settings.serviceTierForRequest = 'default';
assert.equal(read().serviceTier, 'default', '同一结构正确读取标准速度');
settings.serviceTierForRequest = 'fast';
delete parent.__reactFiber$test;
editors[1].__reactFiber$test = attached;
toolbar.hidden = false;
// 同一会话的两个可见组件，速度是否加载不应影响路由身份。
w.document.getElementById('old').removeAttribute('inert');
editors[0].__reactFiber$test = fiber(route('committed'));
assert.equal(read().conversationID, 'committed');
editors[0].__reactFiber$test.updateQueue = {memoCache:{data:[{...settings, serviceTierForRequest:'priority'}]}};
committed.updateQueue = {memoCache:{data:[settings]}};
assert.equal(read().conversationID, 'committed');
assert.equal(read().serviceTierKnown, false, '速度冲突仅降级速度，不丢失模型所属路由');
w.document.getElementById('old').hidden = true;
const dependency = {memoizedValue: route('committed')}; dependency.next = dependency;
committed.dependencies = {firstContext: dependency};
assert.equal(read().conversationID, 'committed', '循环依赖链不能挂起页面');
const cyclic = fiber(route('cycle')); cyclic.return = cyclic;
editors[1].__reactFiber$test = cyclic;
assert.equal(read().routeKind, 'unavailable', '循环祖先链应结束扫描');
dom.window.close();
console.log('活动对话路由：23 项隔离回归检查通过');
